server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://192.168.200.128:3306/cloud_user?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userservice
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HZ # 集群名称
        namespace: 0a27eebf-cbb4-4ff9-bcfe-cdc7e9b143d4 #命名空间 命名空间id
        ephemeral: false
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS